name: build

on:
  push:
    tags:
        - version*
    branches: 
        - dev
        - master     
        - main
  pull_request:
    branches:
        - dev
        - master
        - main

jobs:
  build:

    runs-on: ubuntu-latest
    container: debian:sid

    steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - name: Set up .NET
      run: |
        apt-get -y update
        apt-get -y install aspnetcore-runtime-9.0        
    - name: Build
      run: |        
        dotnet build
