name: build

on:
  push:
    tags:
        - version*
    branches: 
        - dev
        - master     
        - main
  pull_request:
    branches:
        - dev
        - master
        - main

jobs:
  build:

    runs-on: ubuntu-latest
    container: debian:sid

    steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - name: Set up Wget and Libicu
      run: |
        apt update -y -qq
        apt install -y -qqq wget libicu76
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Build
      run: |        
        dotnet build
